#pragma once
// AUTO-GENERATED met.no → icon mapping
// Generated by scripts/convert_icons.py

#include "icon_data.h"

struct IconMapping {
    const char *symbolPrefix;  // met.no symbol_code prefix
    bool        nightVariant;  // true if this is a _night variant
    const uint8_t *dataLarge;  // large icon array
    int         largeSz;       // large icon width/height
    const uint8_t *dataSmall;  // small icon array
    int         smallSz;       // small icon width/height
};

static const IconMapping ICON_MAP[] PROGMEM = {
    {"clearsky_day", false, icon_wx_01d, 80, icon_wxs_01d, 40},
    {"clearsky_night", true, icon_wx_01n, 80, icon_wxs_01n, 40},
    {"clearsky_polartwilight", false, icon_wx_01d, 80, icon_wxs_01d, 40},
    {"fair_day", false, icon_wx_02d, 80, icon_wxs_02d, 40},
    {"fair_night", true, icon_wx_02n, 80, icon_wxs_02n, 40},
    {"fair_polartwilight", false, icon_wx_02d, 80, icon_wxs_02d, 40},
    {"partlycloudy_day", false, icon_wx_022d, 80, icon_wxs_022d, 40},
    {"partlycloudy_night", true, icon_wx_022n, 80, icon_wxs_022n, 40},
    {"partlycloudy_polartwilight", false, icon_wx_022d, 80, icon_wxs_022d, 40},
    {"cloudy", false, icon_wx_04d, 80, icon_wxs_04d, 40},
    {"fog", false, icon_wx_50d, 80, icon_wxs_50d, 40},
    {"heavyrain", false, icon_wx_09d, 80, icon_wxs_09d, 40},
    {"heavyrainandthunder", false, icon_wx_11d, 80, icon_wxs_11d, 40},
    {"heavyrainshowers_day", false, icon_wx_09d, 80, icon_wxs_09d, 40},
    {"heavyrainshowers_night", true, icon_wx_09d, 80, icon_wxs_09d, 40},
    {"heavyrainshowersandthunder_day", false, icon_wx_11d, 80, icon_wxs_11d, 40},
    {"heavyrainshowersandthunder_night", true, icon_wx_11d, 80, icon_wxs_11d, 40},
    {"heavysleet", false, icon_wx_56d, 80, icon_wxs_56d, 40},
    {"heavysleetandthunder", false, icon_wx_11d, 80, icon_wxs_11d, 40},
    {"heavysleetshowers_day", false, icon_wx_56d, 80, icon_wxs_56d, 40},
    {"heavysleetshowers_night", true, icon_wx_56d, 80, icon_wxs_56d, 40},
    {"heavysnow", false, icon_wx_13d, 80, icon_wxs_13d, 40},
    {"heavysnowandthunder", false, icon_wx_11d, 80, icon_wxs_11d, 40},
    {"heavysnowshowers_day", false, icon_wx_13d, 80, icon_wxs_13d, 40},
    {"heavysnowshowers_night", true, icon_wx_13d, 80, icon_wxs_13d, 40},
    {"lightrain", false, icon_wx_51d, 80, icon_wxs_51d, 40},
    {"lightrainandthunder", false, icon_wx_11d, 80, icon_wxs_11d, 40},
    {"lightrainshowers_day", false, icon_wx_10d, 80, icon_wxs_10d, 40},
    {"lightrainshowers_night", true, icon_wx_10n, 80, icon_wxs_10n, 40},
    {"lightsleet", false, icon_wx_56d, 80, icon_wxs_56d, 40},
    {"lightsleetandthunder", false, icon_wx_11d, 80, icon_wxs_11d, 40},
    {"lightsleetshowers_day", false, icon_wx_56d, 80, icon_wxs_56d, 40},
    {"lightsleetshowers_night", true, icon_wx_56d, 80, icon_wxs_56d, 40},
    {"lightsnow", false, icon_wx_71d, 80, icon_wxs_71d, 40},
    {"lightsnowandthunder", false, icon_wx_11d, 80, icon_wxs_11d, 40},
    {"lightsnowshowers_day", false, icon_wx_71d, 80, icon_wxs_71d, 40},
    {"lightsnowshowers_night", true, icon_wx_71d, 80, icon_wxs_71d, 40},
    {"lightssleetshowersandthunder_day", false, icon_wx_11d, 80, icon_wxs_11d, 40},
    {"lightssleetshowersandthunder_night", true, icon_wx_11d, 80, icon_wxs_11d, 40},
    {"lightssnowshowersandthunder_day", false, icon_wx_11d, 80, icon_wxs_11d, 40},
    {"lightssnowshowersandthunder_night", true, icon_wx_11d, 80, icon_wxs_11d, 40},
    {"rain", false, icon_wx_10d, 80, icon_wxs_10d, 40},
    {"rainandthunder", false, icon_wx_11d, 80, icon_wxs_11d, 40},
    {"rainshowers_day", false, icon_wx_10d, 80, icon_wxs_10d, 40},
    {"rainshowers_night", true, icon_wx_10n, 80, icon_wxs_10n, 40},
    {"rainshowersandthunder_day", false, icon_wx_11d, 80, icon_wxs_11d, 40},
    {"rainshowersandthunder_night", true, icon_wx_11d, 80, icon_wxs_11d, 40},
    {"sleet", false, icon_wx_57d, 80, icon_wxs_57d, 40},
    {"sleetandthunder", false, icon_wx_11d, 80, icon_wxs_11d, 40},
    {"sleetshowers_day", false, icon_wx_57d, 80, icon_wxs_57d, 40},
    {"sleetshowers_night", true, icon_wx_57d, 80, icon_wxs_57d, 40},
    {"sleetshowersandthunder_day", false, icon_wx_11d, 80, icon_wxs_11d, 40},
    {"sleetshowersandthunder_night", true, icon_wx_11d, 80, icon_wxs_11d, 40},
    {"snow", false, icon_wx_73d, 80, icon_wxs_73d, 40},
    {"snowandthunder", false, icon_wx_11d, 80, icon_wxs_11d, 40},
    {"snowshowers_day", false, icon_wx_73d, 80, icon_wxs_73d, 40},
    {"snowshowers_night", true, icon_wx_73d, 80, icon_wxs_73d, 40},
    {"snowshowersandthunder_day", false, icon_wx_11d, 80, icon_wxs_11d, 40},
    {"snowshowersandthunder_night", true, icon_wx_11d, 80, icon_wxs_11d, 40},
};
static const int ICON_MAP_COUNT = 59;

// Fallback icon (cloudy)
#define ICON_FALLBACK_LARGE  icon_wx_04d
#define ICON_FALLBACK_SMALL  icon_wxs_04d
#define ICON_FALLBACK_LARGE_SZ  80
#define ICON_FALLBACK_SMALL_SZ  40
